name: Build debug APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build debug APK
      working-directory: AndroidApp
      run: bash ./gradlew assembleDebug --stacktrace
    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: AndroidApp/app/build/outputs/apk/debug/app-debug.apk
