name: Publish release to internal testers

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout- 
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release APK
        working-directory: AndroidApp
        run: bash ./gradlew bundleRelease
      - name: Sign release APK
        id: sign-release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: AndroidApp/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: ${{ steps.sign-release.outputs.signedReleaseFile }}
